/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import TDAs.DB.Consult;
import TDAs.Environment.Ambiente;
import TDAs.Environment.CrearAmbiente;
import TDAs.Environment.Mesa;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Carmina
 */
public class AdmMesas extends javax.swing.JFrame {

    /**
     * Creates new form AdmMesas
     */
    public AdmMesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdMesa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSillas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAmbiente = new javax.swing.JTextField();
        btnAggMesa = new javax.swing.JButton();
        btnUpdateMesa = new javax.swing.JButton();
        btnBuscarMesa = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("IDMesa: ");

        txtIdMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMesaActionPerformed(evt);
            }
        });

        jLabel2.setText("CantidadSillas:");

        txtSillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSillasActionPerformed(evt);
            }
        });

        jLabel3.setText("Ambiente: ");

        btnAggMesa.setText("AgregarMesa");
        btnAggMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggMesaActionPerformed(evt);
            }
        });

        btnUpdateMesa.setText("ModificarMesa");
        btnUpdateMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMesaActionPerformed(evt);
            }
        });

        btnBuscarMesa.setText("BuscarMesa");
        btnBuscarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMesaActionPerformed(evt);
            }
        });

        btnEliminar.setText("EliminarMesa");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnAggMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarMesa)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtSillas, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAmbiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnAggMesa, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnUpdateMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSillasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSillasActionPerformed

    private void txtIdMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMesaActionPerformed

    private void btnAggMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggMesaActionPerformed
        if(isEmpty())
            JOptionPane.showMessageDialog(null,"llene los campos");
        else{
            Ambiente amb = new CrearAmbiente().crearAmbiente(txtAmbiente.getText().toUpperCase());
            Mesa mesa = new Mesa("0", Integer.parseInt(txtSillas.getText()),amb);
            Consult.getInstancia().addMesa(mesa);
            limpiar();
        }
    }//GEN-LAST:event_btnAggMesaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(isEmpty())
            JOptionPane.showMessageDialog(null,"llene los campos");
        else{
            Consult.getInstancia().eliminarMesa(txtIdMesa.getText());
        }
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnUpdateMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMesaActionPerformed
        if(isEmpty())
            JOptionPane.showMessageDialog(null,"llene los campos");
        else{
            Consult.getInstancia().actualizarMesa(txtIdMesa.getText(),Integer.parseInt(txtSillas.getText()),false,txtAmbiente.getText().toUpperCase());
            
        }
        limpiar();
    }//GEN-LAST:event_btnUpdateMesaActionPerformed

    private void btnBuscarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMesaActionPerformed
        if(txtIdMesa.getText().length()>0){
            ResultSet rs = Consult.getInstancia().obtenerMesa(txtIdMesa.getText());
            try{
                ResultSet rsA = Consult.getInstancia().obtenerAmbiente(Integer.toString(rs.getInt(4)));
                txtSillas.setText(Integer.toString(rs.getInt(2)));
                txtAmbiente.setText(rsA.getString(2));
            }
            catch(SQLException ex){
                System.out.println(ex.getMessage());
            }
        }
            
        else{
            JOptionPane.showMessageDialog(null,"Ingrese el ID");
        }
    }//GEN-LAST:event_btnBuscarMesaActionPerformed

    private void limpiar(){
        txtAmbiente.setText("");
        txtIdMesa.setText("");
        txtSillas.setText("");
    }
    
    private boolean isEmpty(){
        return txtAmbiente.getText().equals("") || txtIdMesa.getText().equals("") || txtSillas.getText().equals("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggMesa;
    private javax.swing.JButton btnBuscarMesa;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnUpdateMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAmbiente;
    private javax.swing.JTextField txtIdMesa;
    private javax.swing.JTextField txtSillas;
    // End of variables declaration//GEN-END:variables
}
