/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import TDAs.Actores.Mesero;
import TDAs.Control.CtrlMesero;
import TDAs.DB.Consult;
import TDAs.DB.IngresosDB;
import TDAs.Environment.Mesa;
import TDAs.Ordenes.Cuenta;
import TDAs.Ordenes.Orden;
import TDAs.Ordenes.OrdenNormal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Carmina
 */
public class GuiMesero extends javax.swing.JFrame {

    Cuenta cuenta;
    Mesa mesa;
    Orden orden;
    String mesero = "";
    public GuiMesero(String mesero) {
        this.mesero = mesero;
        initComponents();
        llenarCuentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCrearCuenta = new javax.swing.JButton();
        btnIngresarItem = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbCuenta = new javax.swing.JComboBox<>();
        cmbOrden = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnOrdenNueva = new javax.swing.JButton();
        cmbMesa = new javax.swing.JComboBox<>();
        chbPrioridad = new javax.swing.JCheckBox();
        btnCalcularTiempo = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("IdOrden: ");

        jLabel1.setText("idCuenta:");

        btnCrearCuenta.setText("Crear Cuenta Nueva");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        btnIngresarItem.setText("IngresarItem");
        btnIngresarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarItemActionPerformed(evt);
            }
        });

        btnVerificar.setText("VerMesas");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        jLabel5.setText("Mesas");

        cmbCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCuentaActionPerformed(evt);
            }
        });

        cmbOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrdenActionPerformed(evt);
            }
        });

        btnBuscar.setText("BuscarOrdenes");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnOrdenNueva.setText("Crear Orden nueva");
        btnOrdenNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenNuevaActionPerformed(evt);
            }
        });

        cmbMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chbPrioridad.setText("Prioridad");
        chbPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPrioridadActionPerformed(evt);
            }
        });

        btnCalcularTiempo.setText("CalcularTiempo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbOrden, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbMesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(chbPrioridad)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrearCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrdenNueva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresarItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcularTiempo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(chbPrioridad)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenNueva)
                    .addComponent(btnCrearCuenta)
                    .addComponent(btnIngresarItem)
                    .addComponent(btnBuscar)
                    .addComponent(btnVerificar)
                    .addComponent(btnCalcularTiempo))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        if(!cmbMesa.getSelectedItem().toString().equals("")){
            CtrlMesero.ingresarCuentaNueva(chbPrioridad.isSelected(), cmbMesa.getSelectedItem().toString());
            llenarCuentas();
        }
        else{
            JOptionPane.showMessageDialog(null, "ingrese la mesa");
        }
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnIngresarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarItemActionPerformed
        new RealizarPedido(cmbOrden.getSelectedItem().toString()).setVisible(true);
    }//GEN-LAST:event_btnIngresarItemActionPerformed

    private void llenarCuentas(){
        ResultSet rs= Consult.getInstancia().obtenerCuentas();
        cmbCuenta.removeAllItems();
        cmbOrden.removeAllItems();
        cmbMesa.removeAllItems();
        try {
            if(!rs.getBoolean(9))
                cmbCuenta.addItem(Integer.toString(rs.getInt(1)));
            while(rs.next()){
                if(!rs.getBoolean(9))
                    cmbCuenta.addItem(Integer.toString(rs.getInt(1)));
            }
        } catch (SQLException ex) {
            Logger.getLogger(GuiMesero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void cmbOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrdenActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ResultSet rs = Consult.getInstancia().obtenerOrdenCuenta(cmbCuenta.getSelectedItem().toString());
        cmbOrden.removeAllItems();
        try {
            cmbOrden.addItem(Integer.toString(rs.getInt(1)));
            while(rs.next()){
                cmbOrden.addItem(Integer.toString(rs.getInt(1)));
            }
        } catch (SQLException ex) {
            Logger.getLogger(GuiMesero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnOrdenNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenNuevaActionPerformed
        CtrlMesero.ingresarOrdenNueva(mesero, cmbCuenta.getSelectedItem().toString());
        btnBuscarActionPerformed(evt);
    }//GEN-LAST:event_btnOrdenNuevaActionPerformed

    private void cmbCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuentaActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        ResultSet rs = Consult.getInstancia().obtenerMesaDisponibles();
        cmbMesa.removeAllItems();
        try {
            cmbMesa.addItem(Integer.toString(rs.getInt(1)));
            while(rs.next()){
                cmbMesa.addItem(Integer.toString(rs.getInt(1)));
            }
        } catch (SQLException ex) {
            Logger.getLogger(GuiMesero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void chbPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPrioridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbPrioridadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GuiMesero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCalcularTiempo;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnIngresarItem;
    private javax.swing.JButton btnOrdenNueva;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JCheckBox chbPrioridad;
    private javax.swing.JComboBox<String> cmbCuenta;
    private javax.swing.JComboBox<String> cmbMesa;
    private javax.swing.JComboBox<String> cmbOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
